bruhX3
Red-Space-14/red-space-14 pull request #27
Opened 2023-10-04 17:50 UTC by vandyD

bruuuuuuuuuuuh

## Описание PR
Обновил пару строк и сам перешёл на новую версию сборки

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2023-10-04 18:10 UTC, NULL882 commented
Где текстуры :skull:

2023-10-05 13:53 UTC, NULL882 requested changes
И допиши что-бы при достижении уровня урона до стейта Dead сущность исчезала а не оставалась на месте где её убили.

2023-10-05 13:53 UTC, NULL882 commented on Resources/Prototypes/_Redspace/Entities/Mobs/NPCs/Demons/Demon.yml
> +        path: /Audio/Weapons/Xeno/alien_claw_flesh3.ogg
`Resources/Audio/Effects/demon_attack1.ogg`

2023-10-05 13:53 UTC, NULL882 commented on Resources/Prototypes/_Redspace/Entities/Mobs/NPCs/Demons/Demon.yml
> +        path: /Audio/Weapons/Xeno/alien_claw_flesh3.ogg
`Resources/Audio/Effects/demon_attack1.ogg`

2023-10-05 13:53 UTC, NULL882 commented on Resources/Prototypes/_Redspace/Entities/Mobs/NPCs/Demons/Demon.yml
> +        path: /Audio/Items/bikehorn.ogg
Ладно, тут это можно оставить

2023-10-05 13:53 UTC, NULL882 commented on Resources/Prototypes/_Redspace/Entities/Mobs/NPCs/Demons/Demon_Boss.yml
> +        path: /Audio/Weapons/Xeno/alien_claw_flesh3.ogg
`Resources/Audio/Effects/demon_attack1.ogg`

2023-10-05 13:53 UTC, NULL882 commented on Resources/Prototypes/_Redspace/Entities/Mobs/NPCs/Demons/Demon_Boss.yml
> +        path: /Audio/Weapons/Xeno/alien_claw_flesh3.ogg
`Resources/Audio/Effects/demon_attack1.ogg`

2023-10-05 13:53 UTC, NULL882 commented on Resources/Prototypes/_Redspace/Entities/Mobs/NPCs/Demons/Demon_Boss.yml
> +        path: /Audio/Weapons/Xeno/alien_claw_flesh3.ogg
`Resources/Audio/Effects/demon_attack1.ogg`

2023-10-05 15:05 UTC, vandyD commented on Resources/Prototypes/_Redspace/Entities/Mobs/NPCs/Demons/Demon_Boss.yml
> +        path: /Audio/Weapons/Xeno/alien_claw_flesh3.ogg
Всё готово

2023-10-06 09:33 UTC, NULL882 approved these changes

2023-10-06 09:33 UTC, merged