IPC
Red-Space-14/red-space-14 pull request #28
Opened 2023-10-11 16:50 UTC by vandyD

Наконец! Новая раса КПБ(Комплексный позитронный блок)!

## Описание PR
В этом PR я добавил новую расу! Расу КПБ, у них есть масса преимуществ перед простыми органиками. Например:
1)Им не нужен скафандр чтобы находиться космосе.
2)Сварка не ослепляет их(но флешка всё ещё).
3)Они в отличии от глупых органиков способны починить себя сваркой(хотя тут им понадобится помощь другого существа).
Ну и так далее.

В будущем раса КПБ будет дорабатываться и изменяться 👍 

**Медиа**
<img width="161" alt="image" src="https://github.com/Red-Space-14/red-space-14/assets/131472538/95cd065a-c2b9-4018-be11-76cd6b291af5">

**Проверки**
- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [👍] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [👍] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [👍] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

2023-10-12 11:14 UTC, NULL882 requested changes

2023-10-12 11:14 UTC, NULL882 commented on Resources/Prototypes/_Redspace/Body/Organs/ipc.yml
> +  name: tongue
Думаю правильнее будет `voice module`

2023-10-12 11:14 UTC, NULL882 commented on Resources/Prototypes/_Redspace/Body/Organs/ipc.yml
> +  description: "A fleshy muscle mostly used for lying."
`Мясистая мускула которая обычно используется что бы лгать` это железка а не органик

2023-10-12 11:14 UTC, NULL882 commented on Resources/Prototypes/_Redspace/Body/Organs/ipc.yml
> +  description: "Filters oxygen from an atmosphere, which is then sent into the bloodstream to be used as an electron carrier."
`...фильтруют кислород из атмосферы, после отправляя его в кровеносную систему...` разве у КПБ имеется кровеносная система?

2023-10-12 11:14 UTC, NULL882 commented on Resources/Prototypes/_Redspace/Entities/Mobs/Player/ipc.yml
> +  name: Urist McBorg
Urist McComputer

2023-10-13 10:21 UTC, VictorSShved commented
Можно взять на доработку?

2023-10-13 12:20 UTC, NULL882 commented
Швед 
![HcDniA1fk68](https://github.com/Red-Space-14/red-space-14/assets/104377798/8d6f222a-5473-440f-9e4c-809481603b9a)

2023-10-15 10:46 UTC, NULL882 approved these changes
Повезло тебе

https://github.com/Red-Space-14/red-space-14/assets/104377798/58549b65-2cd8-428d-befc-8a610d25fec5

2023-10-15 10:46 UTC, merged